Bettter error messages for pushover

diff --git a/pushover b/pushover
--- a/pushover
+++ b/pushover
@@ -3,18 +3,23 @@
 # APP_TOKEN="<App token (you can make your own application)>"
 # USER_KEY="<Your user key>"
 #
-source $HOME/.pushover.conf
-MSG="$(hostname): ${@}"
-JSON=$(curl -s \
-  --form-string "token=${APP_TOKEN}" \
-  --form-string "user=${USER_KEY}" \
-  --form-string "message=${MSG}" \
-  https://api.pushover.net/1/messages.json)
+if [ -f "$HOME/.pushover.conf" ]; then
+  source $HOME/.pushover.conf
+  MSG="$(hostname): ${@}"
+  JSON=$(curl -s \
+    --form-string "token=${APP_TOKEN}" \
+    --form-string "user=${USER_KEY}" \
+    --form-string "message=${MSG}" \
+    https://api.pushover.net/1/messages.json)
 
-if [[ "$JSON" == *"\"status\":1"* ]]
-then
-  exit 0;
+  if [[ "$JSON" == *"\"status\":1"* ]]
+  then
+    exit 0;
+  else
+    echo "Error in push: ${JSON}"
+    exit 1;
+  fi
 else
-  echo "Error in push: ${JSON}"
-  exit 1;
+  echo -e "[ERROR] $HOME/.pushover.conf not found\n" \
+	"Should be:\n\nAPP_TOKEN=\"<token here>\"\nUSER_KEY=\"<user key here>\"" 1>&2
 fi
